### ISSUE TITLE
Research on R ecosystem for similar package

### ISSUE THREAD

**Issue by imtvwy** [UBC-MDS/rbccovideda#2]
1. There are around 40 covid related packages found in CRAN
2.  ​Some provide api wrapper to retrieve covid data
https://github.com/taylordunn/canadacovid
https://github.com/epiforecasts/covidregionaldata/
3. Some provide functions to retrieve data, display summary stat and plot
https://github.com/YuLab-SMU/nCov2019
https://github.com/mponce0/covid19.analytic

Our package do #3 on bc local data

**Comment by vtaskaev1** [comment]
Thanks. I have included this to the README's `R Ecosystem` Section.
